create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('BEST_NEW', 'COFFEE', 'LATTE', 'ADE', 'TEA')),
  emoji text not null default '☕',
  name text not null,
  description text not null default '',
  price integer not null check (price >= 0),
  temperature text not null default 'BOTH' check (temperature in ('HOT', 'ICE', 'BOTH')),
  tag text check (tag is null or tag in ('BEST', 'NEW')),
  image_url text,
  image_path text,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menus_category_sort_idx on public.menus (category, sort_order, id);
create index if not exists menus_available_idx on public.menus (available);

drop trigger if exists menus_set_updated_at on public.menus;
create trigger menus_set_updated_at
before update on public.menus
for each row execute function public.set_updated_at();

alter table public.menus enable row level security;

drop policy if exists "customers can read available menus" on public.menus;
create policy "customers can read available menus"
on public.menus for select to anon, authenticated
using (available);

drop policy if exists "admins can read all menus" on public.menus;
create policy "admins can read all menus"
on public.menus for select to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert menus" on public.menus;
create policy "admins can insert menus"
on public.menus for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update menus" on public.menus;
create policy "admins can update menus"
on public.menus for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete menus" on public.menus;
create policy "admins can delete menus"
on public.menus for delete to authenticated
using ((select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('menu-images', 'menu-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can read menu images" on storage.objects;
create policy "public can read menu images"
on storage.objects for select to public
using (bucket_id = 'menu-images');

drop policy if exists "admins can upload menu images" on storage.objects;
create policy "admins can upload menu images"
on storage.objects for insert to authenticated
with check (bucket_id = 'menu-images' and (select public.is_admin()));

drop policy if exists "admins can update menu images" on storage.objects;
create policy "admins can update menu images"
on storage.objects for update to authenticated
using (bucket_id = 'menu-images' and (select public.is_admin()))
with check (bucket_id = 'menu-images' and (select public.is_admin()));

drop policy if exists "admins can delete menu images" on storage.objects;
create policy "admins can delete menu images"
on storage.objects for delete to authenticated
using (bucket_id = 'menu-images' and (select public.is_admin()));

insert into public.menus (id, category, emoji, name, description, price, temperature, tag, available, sort_order) values
  (1,'BEST_NEW','☕','달고나라떼','달콤한 달고나가 올라간 라떼',3000,'BOTH','BEST',true,1),
  (2,'BEST_NEW','🥛','달고나밀크','커피 없이 즐기는 달고나 밀크',2500,'BOTH',null,true,2),
  (3,'BEST_NEW','🍠','우베라떼','달콤하고 부드러운 우베 라떼',3500,'BOTH','NEW',true,3),
  (4,'BEST_NEW','🥛','우베밀크','커피 없이 즐기는 우베 밀크',3000,'BOTH',null,true,4),
  (5,'BEST_NEW','🍨','아이스크림라떼','아이스크림이 올라간 시원한 라떼',3900,'ICE',null,true,5),
  (6,'COFFEE','☕','아메리카노','깔끔하고 고소한 커피',2000,'BOTH',null,true,6),
  (7,'COFFEE','☕','카페라떼','에스프레소와 부드러운 우유',2500,'BOTH',null,true,7),
  (8,'COFFEE','🥛','두유라떼','우유 대신 두유로 만든 라떼',2500,'BOTH',null,true,8),
  (9,'COFFEE','☕','카푸치노','따뜻하게만 제공됩니다',2500,'HOT',null,true,9),
  (10,'COFFEE','☕','바닐라라떼','달콤한 바닐라 라떼',2800,'BOTH',null,true,10),
  (11,'COFFEE','☕','헤이즐넛라떼','고소한 헤이즐넛 라떼',2800,'BOTH',null,true,11),
  (12,'COFFEE','🍫','카페모카','초콜릿과 에스프레소의 조화',3000,'BOTH',null,true,12),
  (13,'COFFEE','☕','카라멜마끼아또','달콤한 카라멜 커피',3000,'BOTH',null,true,13),
  (14,'COFFEE','🥛','돌체라떼','달콤하고 진한 연유 라떼',3000,'BOTH',null,true,14),
  (15,'COFFEE','🥜','투피넛라떼','고소한 견과류 풍미의 라떼',3900,'BOTH',null,true,15),
  (16,'LATTE','🍵','녹차라떼','쌉싸름하고 부드러운 녹차 라떼',3500,'BOTH',null,true,16),
  (17,'LATTE','🍫','초코라떼','달콤하고 진한 초코 라떼',3500,'BOTH',null,true,17),
  (18,'LATTE','🌿','쑥라떼','향긋하고 고소한 쑥 라떼',3500,'BOTH',null,true,18),
  (19,'LATTE','🌾','오곡라떼','차갑게만 제공됩니다',3500,'ICE',null,true,19),
  (20,'LATTE','🍓','딸기라떼','차갑게만 제공됩니다',3900,'ICE',null,true,20),
  (21,'LATTE','🍠','고구마라떼','달콤하고 든든한 고구마 라떼',3900,'BOTH',null,true,21),
  (22,'LATTE','🧋','밀크티','향긋한 홍차와 부드러운 우유',3900,'BOTH',null,true,22),
  (23,'ADE','🍊','청귤에이드','상큼한 청귤 에이드',3500,'ICE',null,true,23),
  (24,'ADE','🍇','청포도에이드','달콤하고 시원한 청포도 에이드',3500,'ICE',null,true,24),
  (25,'ADE','🍋','레몬에이드','상큼하고 시원한 레몬 에이드',3500,'ICE',null,true,25),
  (26,'ADE','🍒','체리에이드','달콤한 체리 에이드',3500,'ICE',null,true,26),
  (27,'TEA','🍑','복숭아아이스티','달콤하고 시원한 복숭아 아이스티',2000,'ICE',null,true,27),
  (28,'TEA','🫖','자스민','향긋한 자스민 허브티',2500,'HOT',null,true,28),
  (29,'TEA','🫖','루이보스','부드럽고 편안한 루이보스티',2500,'HOT',null,true,29),
  (30,'TEA','🌿','페퍼민트','상쾌한 페퍼민트 허브티',2500,'HOT',null,true,30),
  (31,'TEA','🌼','캐모마일','은은하고 향긋한 캐모마일티',2500,'HOT',null,true,31),
  (32,'TEA','🍊','청귤차','달콤하고 상큼한 청귤차',3000,'HOT',null,true,32),
  (33,'TEA','🍊','유자차','향긋하고 달콤한 유자차',3000,'HOT',null,true,33),
  (34,'TEA','🫚','생강차','알싸하고 따뜻한 생강차',3000,'HOT',null,true,34),
  (35,'TEA','🍋','레몬차','상큼하고 따뜻한 레몬차',3500,'HOT',null,true,35),
  (36,'TEA','🍒','오미자차','새콤달콤한 오미자차',3900,'BOTH',null,true,36)
on conflict (id) do update set
  category = excluded.category,
  emoji = excluded.emoji,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  temperature = excluded.temperature,
  tag = excluded.tag,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('public.menus', 'id'), (select max(id) from public.menus), true);

do $$
begin
  alter publication supabase_realtime add table public.menus;
exception when duplicate_object then null;
end $$;

