alter table public.orders
  add column if not exists cancellation_reason text;

create table if not exists public.order_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (order_id, status)
);

create index if not exists order_notifications_user_created_idx
  on public.order_notifications (user_id, created_at desc);

alter table public.order_notifications enable row level security;

drop policy if exists "customers can read own order notifications" on public.order_notifications;
create policy "customers can read own order notifications"
on public.order_notifications for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "customers can mark own notifications read" on public.order_notifications;
create policy "customers can mark own notifications read"
on public.order_notifications for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

do $$
begin
  alter publication supabase_realtime add table public.order_notifications;
exception when duplicate_object then null;
end $$;

-- 이미 존재하는 주문도 알림센터가 비어 보이지 않도록 현재 상태 한 건을 채웁니다.
insert into public.order_notifications (user_id, order_id, status, title, body, read_at, created_at)
select
  user_id,
  id,
  status,
  case status
    when 'preparing' then '음료를 만들고 있어요 🥤'
    when 'ready' then '픽업 준비 완료 🔔'
    when 'picked_up' then '픽업 완료'
    when 'cancelled' then '주문 취소 완료'
    else '주문이 접수됐어요 ☕'
  end,
  case status
    when 'preparing' then '음료를 제조하고 있어요. 조금만 기다려주세요.'
    when 'ready' then '음료가 준비됐어요. 매장에서 픽업해주세요.'
    when 'picked_up' then '힘내개를 이용해주셔서 감사합니다.'
    when 'cancelled' then '주문 결제 취소가 완료됐어요.'
    else '매장에서 주문을 확인하고 있어요.'
  end,
  now(),
  created_at
from public.orders
on conflict (order_id, status) do nothing;

drop function if exists public.request_order_cancel(uuid);

create function public.request_order_cancel(
  p_order_id uuid,
  p_reason text default '고객 앱에서 취소 요청'
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_status text;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  select status into current_status
  from public.orders
  where id = p_order_id and user_id = current_user_id
  for update;

  if current_status is null then
    raise exception 'ORDER_NOT_FOUND';
  end if;

  if current_status = 'cancel_requested' then
    return current_status;
  end if;

  if current_status = 'payment_pending' then
    update public.orders
      set status = 'cancelled',
          payment_status = 'cancelled',
          cancellation_reason = left(coalesce(nullif(trim(p_reason), ''), '결제 전 주문 취소'), 200),
          cancelled_at = now()
    where id = p_order_id;
    insert into public.order_notifications (user_id, order_id, status, title, body)
    values (current_user_id, p_order_id, 'cancelled', '주문 취소 완료', '결제 전 주문이 취소됐어요.')
    on conflict (order_id, status) do nothing;
    return 'cancelled';
  end if;

  -- 결제 완료 주문은 Toss 환불까지 처리하는 cancel-payment Edge Function을 사용해야 합니다.
  raise exception 'DIRECT_PAYMENT_CANCELLATION_REQUIRED';
end;
$$;

revoke all on function public.request_order_cancel(uuid, text) from public, anon;
grant execute on function public.request_order_cancel(uuid, text) to authenticated;
