create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  expo_push_token text not null,
  platform text not null check (platform in ('ios', 'android')),
  device_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists push_tokens_user_token_idx
  on public.push_tokens (user_id, expo_push_token);
create index if not exists push_tokens_user_id_idx on public.push_tokens (user_id);

alter table public.push_tokens enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'push_tokens' and policyname = 'customers can read own push tokens') then
    create policy "customers can read own push tokens"
    on public.push_tokens for select to authenticated
    using ((select auth.uid()) = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'push_tokens' and policyname = 'customers can insert own push tokens') then
    create policy "customers can insert own push tokens"
    on public.push_tokens for insert to authenticated
    with check ((select auth.uid()) = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'push_tokens' and policyname = 'customers can update own push tokens') then
    create policy "customers can update own push tokens"
    on public.push_tokens for update to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);
  end if;
end
$$;
