-- One row per customer order.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default (
    'HNG-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
  ),
  user_id uuid not null references auth.users(id) on delete restrict,
  status text not null default 'paid' check (
    status in ('payment_pending', 'paid', 'accepted', 'preparing', 'ready', 'picked_up', 'cancel_requested', 'cancelled')
  ),
  payment_status text not null default 'pending' check (
    payment_status in ('pending', 'paid', 'cancelled', 'refunded', 'failed')
  ),
  total_amount integer not null check (total_amount >= 0),
  payment_key text unique,
  payment_method text,
  paid_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One row per menu/option combination in an order.
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_id integer not null,
  menu_name text not null,
  temperature text not null check (temperature in ('HOT', 'ICE')),
  extra_shot boolean not null default false,
  soy_milk boolean not null default false,
  personal_tumbler boolean not null default false,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  line_total integer generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create index if not exists orders_user_created_at_idx
  on public.orders (user_id, created_at desc);

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Customers can only read their own orders.
create policy "customers can read own orders"
on public.orders
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "customers can read own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

-- Insert and update policies are intentionally omitted. A payment-verifying
-- Edge Function and the admin backend will use the service role instead.
